name: Michael Cuffaro's Blog
description: Musings, Documenting, Learning, Python, Devops, Lifestyle, Geek stuff.
url: https://blog.cuffaro.com
future: true

markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title

disqus:
    shortname: micuffaro
